# Generated by Django 4.1.5 on 2023-04-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('url', models.CharField(max_length=100, verbose_name='Ссылка на страницу')),
            ],
            options={
                'verbose_name': 'Меню Навигации',
                'verbose_name_plural': 'Меню Навигации',
                'ordering': ['title'],
            },
        ),
    ]
