# Generated by Django 4.1.5 on 2023-04-27 12:49

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_navmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('icon_class', models.CharField(blank=True, max_length=255, verbose_name='Иконка')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, upload_to='%Y/%m/%d', verbose_name='Изображение')),
                ('image_thumbnail', easy_thumbnails.fields.ThumbnailerImageField(upload_to='thumbs/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
    ]
