# Generated by Django 4.1.5 on 2023-05-03 02:38

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_brands_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='image_thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='thumbs/%Y/%m/%d'),
        ),
    ]
