# Generated by Django 4.1.5 on 2023-03-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_singleproduct_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/%d%m%Y', verbose_name='Картина')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Картина Продукта',
                'verbose_name_plural': 'Картины продукта',
            },
        ),
        migrations.RemoveField(
            model_name='singleproduct',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category', verbose_name='Картина'),
        ),
        migrations.AddField(
            model_name='singleproduct',
            name='images',
            field=models.ManyToManyField(blank=True, to='products.productimage', verbose_name='Картина'),
        ),
    ]
