# Generated by Django 4.1.5 on 2023-03-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_singleproduct_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singleproduct',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelManagers(
            name='singleproduct',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='singleproduct',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
