# Generated by Django 4.1.5 on 2023-03-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_singleproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleproduct',
            name='initial_price',
            field=models.BigIntegerField(verbose_name='Цена'),
        ),
    ]
