# Generated by Django 4.1.5 on 2023-04-13 10:51

from django.db import migrations, models
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleproduct',
            name='_content_rendered',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='singleproduct',
            name='content',
            field=precise_bbcode.fields.BBCodeTextField(blank=True, no_rendered_field=True, null=True, verbose_name='Содержание'),
        ),
    ]
