# Generated by Django 4.1.5 on 2023-04-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_singleproduct__content_rendered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleproduct',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Документы'),
        ),
    ]
