# Generated by Django 4.1.5 on 2023-04-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_singleproduct_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Документы'),
        ),
    ]
