# Generated by Django 4.1.5 on 2023-05-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/categories/%Y/%m/%d/', verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='singleproduct',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/produsts/%Y/%m/%d/', verbose_name='Документы'),
        ),
    ]
